export const ASSET_FIELD_VALUE_TYPE = {
  STRING: "FIELD_VALUE_TYPE_STRING",
  MONEY: "FIELD_VALUE_TYPE_MONEY",
  TIMESTAMP: "FIELD_VALUE_TYPE_TIMESTAMP",
};

export const ASSET_FIELD_LABEL = {
  TEXT: "Text",
  CURR: "Currency",
  DATE: "Date",
};

export const ASSET_FIELD_MAPPED: any = {
  [ASSET_FIELD_VALUE_TYPE.STRING]: ASSET_FIELD_LABEL.TEXT,
  [ASSET_FIELD_VALUE_TYPE.MONEY]: ASSET_FIELD_LABEL.CURR,
  [ASSET_FIELD_VALUE_TYPE.TIMESTAMP]: ASSET_FIELD_LABEL.DATE,
};
