export const PAGINATION = {
  DEFAULT_PAGE: 1,
  TOTAL_PAGES: 1,
  TOTAL_RECORDS: 0,
  PAGE_LIMIT: 10,
  PAGE_KEY_NAME: "page",
  LIMIT_KEY_NAME: "limit",
  DROPDOWNS_RECORD_LIMIT: 50,
  OPTIONAL_PAGE_LIMIT: 5,
  ROWS_PER_PAGE_OPTIONS: [1, 5, 10, 15, 20],
} as const;
