import type { Metadata } from "next";
import "./globals.css";
import { RootLayout } from "@/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayouts({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RootLayout>{children}</RootLayout>
    </html>
  );
}
